const categorizedSkills = {
  language: {
    title: 'Programming Languages',
    skills: ['c', 'cplusplus', 'csharp', 'go', 'java', 'javascript', 'typescript', 'php', 'perl', 'ruby', 'scala', 'python', 'swift', 'objectivec', 'clojure', 'rust', 'haskell', 'coffeescript', 'elixir', 'erlang', 'nim'],
  },

  frontend_dev: {
    title: 'Frontend Development',
    skills: ['vuejs', 'react', 'svelte', 'angularjs', 'backbonejs', 'materialui', 'bootstrap', 'vuetify', 'css3', 'html5', 'pug', 'gulp', 'sass', 'redux', 'webpack', 'babel', 'tailwind', 'materialize', 'bulma', 'gtk', 'qt', 'wx_widgets', 'ember'],
  },

  backend_dev: {
    title: 'Backend Development',
    skills: ['nodejs', 'denojs', 'spring', 'express', 'graphql', 'kafka', 'solr', 'rabbitMQ', 'hadoop', 'nginx', 'openresty', 'nestjs'],
  },

  mobile_dev: {
    title: 'Mobile App Development',
    skills: ['android', 'flutter', 'dart', 'kotlin', 'nativescript', 'xamarin', 'reactnative', 'ionic', 'apachecordova'],
  },

  ai: {
    title: 'AI/ML',
    skills: ['tensorflow', 'pytorch', 'pandas', 'seaborn', 'opencv', 'scikit_learn'],
  },

  database: {
    title: 'Database',
    skills: ['mongodb', 'mysql', 'postgresql', 'redis', 'oracle', 'cassandra', 'couchdb', 'hive', 'realm', 'mariadb', 'cockroachdb', 'elasticsearch', 'sqlite', 'mssql'],
  },

  data_visualization: {
    title: 'Data Visualization',
    skills: ['d3js', 'chartjs', 'canvasjs', 'kibana', 'grafana'],
  },

  devops: {
    title: 'Devops',
    skills: ['aws', 'docker', 'jenkins', 'gcp', 'kubernetes', 'bash', 'azure', 'vagrant', 'circleci', 'travisci'],
  },

  baas: {
    title: 'Backend as a Service(BaaS)',
    skills: ['firebase', 'appwrite', 'amplify', 'heroku'],
  },

  framework: {
    title: 'Framework',
    skills: ['django', 'dotnet', 'electron', 'symfony', 'laravel', 'codeigniter', 'rails', 'flask', 'quasar', 'zend'],
  },

  testing: {
    title: 'Testing',
    skills: ['cypress', 'selenium', 'jest', 'mocha', 'puppeteer', 'karma', 'jasmine'],
  },

  software: {
    title: 'Software',
    skills: ['illustrator', 'photoshop', 'xd', 'aftereffects', 'figma', 'blender', 'sketch', 'invision', 'framer', 'matlab', 'postman', 'insomnia'],
  },

  static_site_generator: {
    title: 'Static Site Generators',
    skills: ['gatsby', 'gridsome', 'hugo', 'jekyll', 'nextjs', 'nuxtjs', '11ty', 'scully', 'sculpin', 'sapper', 'vuepress', 'hexo', 'middleman'],
  },

  game_engines: {
    title: 'Game Engines',
    skills: ['unity', 'unreal', 'godot'],
  },

  automation: {
    title: 'Automation',
    skills: ['zapier', 'ifttt'],
  },

  other: {
    title: 'Other',
    skills: ['linux', 'git', 'arduino'],
  },
};

const icons = {
  materialui: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-plain.svg',
  godot: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/godot/godot-original.svg',
  denojs: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/denojs/denojs-original.svg',
  insomnia: 'https://seeklogo.com/images/I/insomnia-logo-A35E09EB19-seeklogo.com.png',
  zend: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/zend/zend-plain.svg',
  vuejs: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
  react: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
  angularjs: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-plain.svg',
  aws: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg',
  android: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/android/android-original-wordmark.svg',
  arduino: 'https://cdn.worldvectorlogo.com/logos/arduino-1.svg',
  backbonejs: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/backbonejs/backbonejs-original.svg',
  bootstrap: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg',
  c: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-plain.svg',
  canvasjs: 'https://raw.githubusercontent.com/Hardik0307/Hardik0307/master/assets/canvasjs-charts.svg',
  coffeescript: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/coffeescript/coffeescript-original.svg',
  codeigniter: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/codeigniter/codeigniter-plain.svg',
  cplusplus: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-plain.svg',
  css3: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg',
  csharp: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-plain.svg',
  d3js: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/d3js/d3js-original.svg',
  django: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg',
  docker: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg',
  dotnet: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dot-net/dot-net-plain.svg',
  electron: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/electron/electron-original.svg',
  express: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg',
  go: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original-wordmark.svg',
  graphql: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg',
  gulp: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gulp/gulp-plain.svg',
  html5: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg',
  hugo: 'https://api.iconify.design/logos-hugo.svg',
  java: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
  javascript: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg',
  ionic: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Ionic_Logo.svg',
  laravel: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-plain.svg',
  meteor: 'https://devicons.github.io/devicon/devicon.git/icons/meteor/meteor-original-wordmark.svg',
  mongodb: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg',
  mysql: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg',
  nestjs: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/nestjs/nestjs-plain.svg',
  nginx: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg',
  nodejs: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg',
  openresty: 'https://openresty.org/images/logo.png',
  oracle: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/oracle/oracle-original.svg',
  aftereffects: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/aftereffects/aftereffects-plain.svg',
  photoshop: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg',
  xd: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xd/xd-plain.svg',
  php: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-plain.svg',
  perl: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/perl/perl-original.svg',
  postgresql: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-plain.svg',
  python: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-plain.svg',
  rails: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rails/rails-plain.svg',
  redis: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/redis/redis-original-wordmark.svg',
  ruby: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-plain.svg',
  rust: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-plain.svg',
  sass: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg',
  scala: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scala/scala-plain.svg',
  solidworks: 'https://cdn.worldvectorlogo.com/logos/solidworks.svg',
  symfony: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/symfony/symfony-original.svg',
  spring: 'https://www.vectorlogo.zone/logos/springio/springio-icon.svg',
  swift: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-plain.svg',
  typescript: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-plain.svg',
  linux: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg',
  redux: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg',
  webpack: 'https://raw.githubusercontent.com/devicons/devicon/d00d0969292a6569d45b06d3f350f463a0107b0d/icons/webpack/webpack-original-wordmark.svg',
  flutter: 'https://www.vectorlogo.zone/logos/flutterio/flutterio-icon.svg',
  dart: 'https://www.vectorlogo.zone/logos/dartlang/dartlang-icon.svg',
  kotlin: 'https://www.vectorlogo.zone/logos/kotlinlang/kotlinlang-icon.svg',
  tensorflow: 'https://www.vectorlogo.zone/logos/tensorflow/tensorflow-icon.svg',
  chartjs: 'https://www.chartjs.org/media/logo-title.svg',
  jenkins: 'https://www.vectorlogo.zone/logos/jenkins/jenkins-icon.svg',
  gcp: 'https://www.vectorlogo.zone/logos/google_cloud/google_cloud-icon.svg',
  kubernetes: 'https://www.vectorlogo.zone/logos/kubernetes/kubernetes-icon.svg',
  azure: 'https://www.vectorlogo.zone/logos/microsoft_azure/microsoft_azure-icon.svg',
  git: 'https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg',
  kafka: 'https://www.vectorlogo.zone/logos/apache_kafka/apache_kafka-icon.svg',
  solr: 'https://www.vectorlogo.zone/logos/apache_solr/apache_solr-icon.svg',
  cassandra: 'https://www.vectorlogo.zone/logos/apache_cassandra/apache_cassandra-icon.svg',
  rabbitMQ: 'https://www.vectorlogo.zone/logos/rabbitmq/rabbitmq-icon.svg',
  hadoop: 'https://www.vectorlogo.zone/logos/apache_hadoop/apache_hadoop-icon.svg',
  bash: 'https://www.vectorlogo.zone/logos/gnu_bash/gnu_bash-icon.svg',
  pytorch: 'https://www.vectorlogo.zone/logos/pytorch/pytorch-icon.svg',
  pandas: 'https://raw.githubusercontent.com/devicons/devicon/2ae2a900d2f041da66e950e4d48052658d850630/icons/pandas/pandas-original.svg',
  seaborn: 'https://seaborn.pydata.org/_images/logo-mark-lightbg.svg',
  opencv: 'https://www.vectorlogo.zone/logos/opencv/opencv-icon.svg',
  illustrator: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg',
  figma: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg',
  blender: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/blender/blender-original.svg',
  babel: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/babel/babel-original.svg',
  sketch: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sketch/sketch-original.svg',
  flask: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg',
  nativescript: 'https://raw.githubusercontent.com/detain/svg-logos/780f25886640cef088af994181646db2f6b1a3f8/svg/nativescript.svg',
  xamarin: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xamarin/xamarin-original.svg',
  vagrant: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vagrant/vagrant-plain.svg',
  tailwind: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg',
  materialize: 'https://raw.githubusercontent.com/prplx/svg-logos/5585531d45d294869c4eaab4d7cf2e9c167710a9/svg/materialize.svg',
  invision: 'https://www.vectorlogo.zone/logos/invisionapp/invisionapp-icon.svg',
  framer: 'https://www.vectorlogo.zone/logos/framer/framer-icon.svg',
  bulma: 'https://raw.githubusercontent.com/gilbarbara/logos/804dc257b59e144eaca5bc6ffd16949752c6f789/logos/bulma.svg',
  couchdb: 'https://raw.githubusercontent.com/devicons/devicon/0d6c64dbbf311879f7d563bfc3ccf559f9ed111c/icons/couchdb/couchdb-original.svg',
  firebase: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg',
  amplify: 'https://docs.amplify.aws/assets/logo-dark.svg',
  hive: 'https://www.vectorlogo.zone/logos/apache_hive/apache_hive-icon.svg',
  realm: 'https://raw.githubusercontent.com/bestofjs/bestofjs-webui/8665e8c267a0215f3159df28b33c365198101df5/public/logos/realm.svg',
  gatsby: 'https://www.vectorlogo.zone/logos/gatsbyjs/gatsbyjs-icon.svg',
  gridsome: 'https://www.vectorlogo.zone/logos/gridsome/gridsome-icon.svg',
  nuxtjs: 'https://www.vectorlogo.zone/logos/nuxtjs/nuxtjs-icon.svg',
  jekyll: 'https://www.vectorlogo.zone/logos/jekyllrb/jekyllrb-icon.svg',
  nextjs: 'https://cdn.worldvectorlogo.com/logos/nextjs-2.svg',
  reactnative: 'https://reactnative.dev/img/header_logo.svg',
  mariadb: 'https://www.vectorlogo.zone/logos/mariadb/mariadb-icon.svg',
  cockroachdb: 'https://cdn.worldvectorlogo.com/logos/cockroachdb.svg',
  objectivec: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/objectivec/objectivec-plain.svg',
  clojure: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/clojure/clojure-line.svg',
  haskell: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/haskell/haskell-original.svg',
  svelte: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-plain.svg',
  vuetify: 'https://bestofjs.org/logos/vuetify.svg',
  pug: 'https://cdn.worldvectorlogo.com/logos/pug.svg',
  mocha: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mocha/mocha-plain.svg',
  jest: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg',
  cypress: 'https://raw.githubusercontent.com/simple-icons/simple-icons/6e46ec1fc23b60c8fd0d2f2ff46db82e16dbd75f/icons/cypress.svg',
  selenium: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/selenium/selenium-original.svg',
  puppeteer: 'https://www.vectorlogo.zone/logos/pptrdev/pptrdev-official.svg',
  karma: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/karma/karma-original.svg',
  jasmine: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jasmine/jasmine-plain.svg',
  gtk: 'https://upload.wikimedia.org/wikipedia/commons/7/71/GTK_logo.svg',
  qt: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Qt_logo_2016.svg',
  wx_widgets: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/WxWidgets.svg',
  ember: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/ember/ember-original-wordmark.svg',
  scikit_learn: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit_learn_logo_small.svg',
  quasar: 'https://cdn.quasar.dev/logo/svg/quasar-logo.svg',
  kibana: 'https://www.vectorlogo.zone/logos/elasticco_kibana/elasticco_kibana-icon.svg',
  grafana: 'https://www.vectorlogo.zone/logos/grafana/grafana-icon.svg',
  elasticsearch: 'https://www.vectorlogo.zone/logos/elastic/elastic-icon.svg',
  circleci: 'https://www.vectorlogo.zone/logos/circleci/circleci-icon.svg',
  scully: 'https://raw.githubusercontent.com/scullyio/scully/main/assets/logos/SVG/scullyio-icon.svg',
  '11ty': 'https://gist.githubusercontent.com/vivek32ta/c7f7bf583c1fb1c58d89301ea40f37fd/raw/f4c85cce5790758286b8f155ef9a177710b995df/11ty.svg',
  sculpin: 'https://gist.githubusercontent.com/vivek32ta/c7f7bf583c1fb1c58d89301ea40f37fd/raw/1782aef8672484698c0dd407f900c4a329ed5bc4/sculpin.svg',
  sapper: 'https://raw.githubusercontent.com/bestofjs/bestofjs-webui/master/public/logos/sapper.svg',
  vuepress: 'https://raw.githubusercontent.com/AliasIO/wappalyzer/master/src/drivers/webextension/images/icons/VuePress.svg',
  unity: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg',
  unreal: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unrealengine/unrealengine-original.svg',
  elixir: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elixir/elixir-plain.svg',
  heroku: 'https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg',
  appwrite: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/appwrite/appwrite-plain.svg',
  hexo: 'https://www.vectorlogo.zone/logos/hexoio/hexoio-icon.svg',
  travisci: 'https://www.vectorlogo.zone/logos/travis-ci/travis-ci-icon.svg',
  apachecordova: 'https://www.vectorlogo.zone/logos/apache_cordova/apache_cordova-icon.svg',
  zapier: 'https://www.vectorlogo.zone/logos/zapier/zapier-icon.svg',
  ifttt: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ifttt/ifttt-original.svg',
  postman: 'https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg',
  erlang: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/erlang/erlang-plain.svg',
  nim: 'https://www.vectorlogo.zone/logos/nim-lang/nim-lang-icon.svg',
  sqlite: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-plain.svg',
  mssql: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg',
  middleman: 'https://raw.githubusercontent.com/leungwensen/svg-icon/b84b3f3a3da329b7c1d02346865f8e98beb05413/dist/svg/logos/middleman.svg',
  matlab: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/matlab/matlab-plain.svg',
};

const skillWebsites = {
  materialui: 'https://mui.com/',
  godot: 'https://godotengine.org/',
  denojs: 'https://deno.land/',
  insomnia: 'https://insomnia.rest/',
  zend: 'https://framework.zend.com/',
  arduino: 'https://www.arduino.cc/',
  solidworks: 'https://www.solidworks.com/',
  vuejs: 'https://vuejs.org/',
  react: 'https://reactjs.org/',
  angularjs: 'https://angular.io',
  angular: 'https://angular.io',
  aws: 'https://aws.amazon.com',
  android: 'https://developer.android.com',
  backbonejs: 'https://backbonejs.org',
  bootstrap: 'https://getbootstrap.com',
  c: 'https://www.cprogramming.com/',
  canvasjs: 'https://canvasjs.com',
  coffeescript: 'https://offeescript.org',
  codeigniter: 'https://codeigniter.com',
  cplusplus: 'https://www.w3schools.com/cpp/',
  css3: 'https://www.w3schools.com/css/',
  csharp: 'https://www.w3schools.com/cs/',
  d3js: 'https://d3js.org/',
  django: 'https://www.djangoproject.com/',
  docker: 'https://www.docker.com/',
  dotnet: 'https://dotnet.microsoft.com/',
  electron: 'https://www.electronjs.org',
  express: 'https://expressjs.com',
  go: 'https://golang.org',
  graphql: 'https://graphql.org',
  gulp: 'https://gulpjs.com',
  html5: 'https://www.w3.org/html/',
  hugo: 'https://gohugo.io/',
  java: 'https://www.java.com',
  javascript: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  ionic: 'https://ionicframework.com',
  laravel: 'https://laravel.com/',
  matlab: 'https://www.mathworks.com/',
  meteor: 'https://www.meteor.com/',
  mongodb: 'https://www.mongodb.com/',
  mysql: 'https://www.mysql.com/',
  nestjs: 'https://nestjs.com/',
  nginx: 'https://www.nginx.com',
  nodejs: 'https://nodejs.org',
  openresty: 'https://openresty.org/',
  oracle: 'https://www.oracle.com/',
  photoshop: 'https://www.photoshop.com/en',
  xd: 'https://www.adobe.com/products/xd.html',
  php: 'https://www.php.net',
  perl: 'https://www.perl.org/',
  postgresql: 'https://www.postgresql.org',
  python: 'https://www.python.org',
  rails: 'https://rubyonrails.org',
  redis: 'https://redis.io',
  ruby: 'https://www.ruby-lang.org/en/',
  rust: 'https://www.rust-lang.org',
  sass: 'https://sass-lang.com',
  scala: 'https://www.scala-lang.org',
  symfony: 'https://symfony.com',
  spring: 'https://spring.io/',
  swift: 'https://developer.apple.com/swift/',
  typescript: 'https://www.typescriptlang.org/',
  linux: 'https://www.linux.org/',
  redux: 'https://redux.js.org',
  webpack: 'https://webpack.js.org',
  flutter: 'https://flutter.dev',
  dart: 'https://dart.dev',
  kotlin: 'https://kotlinlang.org',
  tensorflow: 'https://www.tensorflow.org',
  chartjs: 'https://www.chartjs.org',
  jenkins: 'https://www.jenkins.io',
  gcp: 'https://cloud.google.com',
  kubernetes: 'https://kubernetes.io',
  azure: 'https://azure.microsoft.com/en-in/',
  git: 'https://git-scm.com/',
  kafka: 'https://kafka.apache.org/',
  solr: 'https://lucene.apache.org/solr/',
  cassandra: 'https://cassandra.apache.org/',
  rabbitMQ: 'https://www.rabbitmq.com',
  hadoop: 'https://hadoop.apache.org/',
  bash: 'https://www.gnu.org/software/bash/',
  pytorch: 'https://pytorch.org/',
  pandas: 'https://pandas.pydata.org/',
  seaborn: 'https://seaborn.pydata.org/',
  opencv: 'https://opencv.org/',
  illustrator: 'https://www.adobe.com/in/products/illustrator.html',
  figma: 'https://www.figma.com/',
  blender: 'https://www.blender.org/',
  babel: 'https://babeljs.io/',
  sketch: 'https://www.sketch.com/',
  flask: 'https://flask.palletsprojects.com/',
  nativescript: 'https://nativescript.org/',
  xamarin: 'https://dotnet.microsoft.com/apps/xamarin',
  vagrant: 'https://www.vagrantup.com/',
  tailwind: 'https://tailwindcss.com/',
  materialize: 'https://materializecss.com/',
  invision: 'https://www.invisionapp.com/',
  framer: 'https://www.framer.com/',
  bulma: 'https://bulma.io/',
  couchdb: 'https://couchdb.apache.org/',
  firebase: 'https://firebase.google.com/',
  amplify: 'https://aws.amazon.com/amplify/',
  hive: 'https://hive.apache.org/',
  realm: 'https://realm.io/',
  gatsby: 'https://www.gatsbyjs.com/',
  gridsome: 'https://gridsome.org/',
  nuxtjs: 'https://nuxtjs.org/',
  jekyll: 'https://jekyllrb.com/',
  nextjs: 'https://nextjs.org/',
  reactnative: 'https://reactnative.dev/',
  mariadb: 'https://mariadb.org/',
  cockroachdb: 'https://www.cockroachlabs.com/product/cockroachdb/',
  objectivec: 'https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html',
  clojure: 'https://clojure.org/',
  haskell: 'https://www.haskell.org/',
  svelte: 'https://svelte.dev',
  vuetify: 'https://vuetifyjs.com/en/',
  pug: 'https://pugjs.org',
  mocha: 'https://mochajs.org',
  jest: 'https://jestjs.io',
  cypress: 'https://www.cypress.io',
  selenium: 'https://www.selenium.dev',
  puppeteer: 'https://github.com/puppeteer/puppeteer',
  karma: 'https://karma-runner.github.io/latest/index.html',
  jasmine: 'https://jasmine.github.io/',
  gtk: 'https://www.gtk.org/',
  qt: 'https://www.qt.io/',
  wx_widgets: 'https://www.wxwidgets.org/',
  ember: 'https://emberjs.com/',
  scikit_learn: 'https://scikit-learn.org/',
  quasar: 'https://quasar.dev/',
  kibana: 'https://www.elastic.co/kibana',
  grafana: 'https://grafana.com',
  elasticsearch: 'https://www.elastic.co',
  circleci: 'https://circleci.com',
  scully: 'https://scully.io/',
  sculpin: 'https://sculpin.io/',
  '11ty': 'https://www.11ty.dev/',
  sapper: 'https://sapper.svelte.dev/',
  vuepress: 'https://vuepress.vuejs.org/',
  unity: 'https://unity.com/',
  unreal: 'https://unrealengine.com/',
  hexo: 'hexo.io/',
  heroku: 'https://heroku.com',
  appwrite: 'https://appwrite.io',
  zapier: 'https://zapier.com',
  ifttt: 'https://ifttt.com/',
  elixir: 'https://elixir-lang.org',
  travisci: 'https://travis-ci.org',
  apachecordova: 'https://cordova.apache.org/',
  sqlite: 'https://www.sqlite.org/',
  mssql: 'https://www.microsoft.com/en-us/sql-server',
  postman: 'https://postman.com',
  erlang: 'https://www.erlang.org/',
  nim: 'https://nim-lang.org/',
  middleman: 'https://middlemanapp.com/',
};

const initialSkillState = {};

const skillsArray = Object.keys(categorizedSkills).map((key) => categorizedSkills[key].skills);
const skills = [].concat.apply([], skillsArray).sort();

skills.forEach((skill) => {
  initialSkillState[skill] = false;
});

const categories = Object.keys(categorizedSkills);

export { initialSkillState, icons, skills, skillWebsites, categorizedSkills, categories };
